name = ("Vlad Verheij")
jumpforce = ("9.8")
ability = ("Slowing down time")
speed = ("8")
vehicle = ("Train")
lives_left = ("1")
languages = ("3")
age = ("15")
wanted = False

print("Character Stats:")
print("----------------")
print("Character Name:", name)
print("Jump power:", jumpforce)
print("Special ability:", ability)
print("Movement speed:", speed)
print("Vehicles unlocked:", vehicle)
print("Lives left:", lives_left)
print("Number of spoken languages:", languages)
print("Current age:", age)
print("Wanted status:", wanted)
print("----------------")